### ISSUE TITLE
Bad link not resetting

### ISSUE THREAD

**Issue by mkolehmainen** [org-zpr/zpr-core#877]
We had a bug a while back where links from adapters did not reset so you have to restart the node to reconnect an adapter.  This is a similar bug.

To reproduce:
- create a simple policy, set up to allow a client adapter to connect with boostrap auth.
- Start the node and visa service  and visa service adapter.
- Now MISCONFIGURE the client adapter. Don't put in the "bootstrap" key, instead add an "authentication" section.  Eg

```toml
[adapter]
node_addr = "..."
node_public_key_file = "..."
# bootstrap_key = "adapter-cli-bas.key"

[authentication]
bas_key = "adapter-cli-bas.key"
```
Note that the `bootstrap_key` property is commented out.  

Now when that connects the adapter will try to open a connection to the authentication service which will generate a visa request which is denied because the node never sent an authentication message to the visa service with the client address in it. 

Now quit the client adapter and wait a bit.

Then fix the config file by comment out the whole `authentication` block and re-enabling the `bootstrap_key` property.  Start the correctly configured client adapter and ... node and adapter are not able to establish a connection.  Seems like there is some state remaining on the node that is causing this (Just a guess).
